function flag = startMenu(flag)

f = figure('Name', 'Matlab project', ...
             'NumberTitle', 'off', ...
             'Position', [800 400 350 250], ...
             'MenuBar', 'none', ...
             'ToolBar', 'none');

textHandle = uicontrol('Style', 'text', ...
                       'String', 'Progetto MATLAB di Carlo Ancri', ...
                       'Position', [50 90 250 80], ...
                       'HorizontalAlignment', 'center', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor', get(f,'Color'));

visualizeDT = (flag == 1);
checkboxHandle = uicontrol('Style', 'checkbox', ...
                             'String', 'Visualize DT graphs', ...
                             'Value', visualizeDT, ...
                             'Position', [100 50 170 20], ...
                             'Callback', @(src, event) updateFlag(src));

startButton = uicontrol('Style', 'pushbutton', ...
                        'String', 'Start program', ...
                        'Position', [100 20 150 30], ...
                        'Callback', @(src, event) close(f));

  function updateFlag(source)
    if get(source, 'Value')
      flag = 1;
    else
      flag = 0;
    end
  end

waitfor(f);
end